name: buildWindows
on: workflow_dispatch
jobs:
  buildAll:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Fetch Dependencies
        run: ant -f buildscripts/fetchdeps.xml
      - name: Build with Ant
        run: ant stage -Dmm.build.failonerror=false
